version: "3.9"
services:
  app:
    build:
      context: ..
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    # Sleep 1 until Postgres is up.
    # Once up, uvicorn app.main:app --host 0.0.0.0 runs.
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done; alembic upgrade head; uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DB_URL=postgresql+asyncpg://devuser:changeme@db:5432/devdb?async_fallback=True
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data: