"""Main tables

Revision ID: 75f073ed97dd
Revises: 3f3ddb3de0a6
Create Date: 2024-04-05 12:33:31.907034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75f073ed97dd"
down_revision: Union[str, None] = "3f3ddb3de0a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_currency_id"), "currency", ["id"], unique=False)
    op.create_table(
        "account",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("summ", sa.Float(), nullable=False),
        sa.Column("is_savings_account", sa.Boolean(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("fk_currency_id", sa.Integer(), nullable=False),
        sa.Column("fk_user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=False)
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("fk_currency_id", sa.Integer(), nullable=False),
        sa.Column("fk_user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_category_id"), "category", ["id"], unique=False)
    op.create_table(
        "savingsaccount",
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("fk_account_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savingsaccount_id"), "savingsaccount", ["id"], unique=False
    )
    op.create_table(
        "subcategory",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fk_category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subcategory_id"), "subcategory", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subcategory_id"), table_name="subcategory")
    op.drop_table("subcategory")
    op.drop_index(op.f("ix_savingsaccount_id"), table_name="savingsaccount")
    op.drop_table("savingsaccount")
    op.drop_index(op.f("ix_category_id"), table_name="category")
    op.drop_table("category")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_currency_id"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
