"""Account image_url nullable True

Revision ID: da40b5c07776
Revises: 5335ed34ea2a
Create Date: 2024-04-09 14:01:43.959227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da40b5c07776"
down_revision: Union[str, None] = "5335ed34ea2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account", "image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account", "image_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
